version: '3.9'

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend-api:
    build: ./backend-api
    restart: unless-stopped
    env_file:
      - ./backend-api/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/accidents
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  hospital-dashboard:
    build: ./hospital-dashboard
    restart: unless-stopped
    environment:
      - VITE_BACKEND_URL=http://localhost:4000
      - VITE_MAPBOX_TOKEN=${MAPBOX_TOKEN}
    ports:
      - "5173:80"
    depends_on:
      - backend-api

volumes:
  mongo_data:


